version: "3.9"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MySQLPassword
    ports:
      - "3306:3306"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
  php:
      image: php:7.3-apache
      build:
        context: .
        dockerfile: dockerfile
      depends_on:
        db:
          condition: service_healthy
      volumes:
      - ./site:/var/www/html/
      ports:
      - 8081:80